Restaurante_Delicias/Controllers/EcommerceController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using Microsoft.Data.SqlClient;
using Newtonsoft.Json;
using Restaurante_Delicias.ADO;
using Restaurante_Delicias.Models;

namespace Restaurante_Delicias.Controllers
{
    public class EcommerceController : Controller
    {
        //Definir Interfaces
        private IProductoADO productoADO;
        private IDet_boletaADO det_BoletaADO;
        private ICab_boletaADO cab_BoletaADO;

        public EcommerceController()
        {
            productoADO = new ProductoADO();
            det_BoletaADO = new Det_boletaADO();
            cab_BoletaADO = new Cab_boletaADO();
        }

        //Listar Catalogo
        public async Task<IActionResult> Catalogo()
        {
            if (HttpContext.Session.GetString("Carrito") == null)
            {
                HttpContext.Session.SetString("Carrito", JsonConvert.SerializeObject(new List<Det_boleta>()));
                ViewBag.count = 0;
            }
            else
            {
                contador();
            }

            return View(await Task.Run(() => productoADO.listarProductos()));
        }

        //Obtener Productos
        public Producto Obtener(int id)
        {
            Producto obj = productoADO.listarProductos().Where(p => p.id_prod == id).FirstOrDefault();
            if(obj == null)
            {
                obj = new Producto();
            }
            return obj;
        }

        public async Task<IActionResult> Agregar(int id)
        {
            contador();
            return View(await Task.Run(() => Obtener(id)));
        }

        [HttpPost]
        public ActionResult Agregar(int id, int cantidad)
        {
            Producto obj = Obtener(id);
            if (obj != null)
            {
                if (cantidad <= 0)
                {
                    ViewBag.mensaje = "Ingrese una cantidad mayor a cero.";
                    return View(obj);
                }

                if (obj.cantidad < cantidad)
                {
                    ViewBag.mensaje = string.Format("El producto solo dispone de {0} unidades", obj.cantidad);
                    return View(obj);
                }
                else
                {
                    Det_boleta detalle = new Det_boleta()
                    {
                        id_prod = obj.id_prod,
                        nom_prod = obj.nom_prod,
                        precio = obj.precio,
                        cantidad = cantidad
                    };

                    List<Det_boleta> carrito = JsonConvert.DeserializeObject<List<Det_boleta>>(HttpContext.Session.GetString("Carrito"));

                    // Verificar si el producto existe
                    Det_boleta temp = carrito.Find(i => i.id_prod == id);
                    if (temp == null)
                    {
                        carrito.Add(detalle);
                    }
                    else
                    {
                        temp.cantidad = detalle.cantidad;
                    }

                    HttpContext.Session.SetString("Carrito", JsonConvert.SerializeObject(carrito));
                    return RedirectToAction("Carrito");
                }
            }
            else
            {
                return RedirectToAction("Catalogo");
            }
        }

        //Agregar a carrito
        public ActionResult Carrito()
        {
            if (HttpContext.Session.GetString("Carrito") == null)
            {
                return RedirectToAction("Catalogo");
            }
            IEnumerable<Det_boleta> carrito = JsonConvert.DeserializeObject<List<Det_boleta>>(HttpContext.Session.GetString("Carrito"));
            if (carrito.Count() == 0)
            {
                return RedirectToAction("Catalogo");
            }

            ViewBag.count = carrito.Count();
            ViewBag.total = carrito.Sum(i => i.importe);
            return View(carrito);
        }

        //Quitar de carrito
        public IActionResult Quitar(int id)
        {
            List<Det_boleta> carrito = JsonConvert.DeserializeObject<List<Det_boleta>>(HttpContext.Session.GetString("Carrito"));
            if (carrito == null || id <= 0)
            {
                return RedirectToAction("Catalogo");
            }
            Det_boleta obj = carrito.Where(i => i.id_prod == id).First();
            if (obj != null)
            {
                carrito.Remove(obj);
                HttpContext.Session.SetString("Carrito", JsonConvert.SerializeObject(carrito));
            }
            else
            {
                ViewBag.mensaje = "Ocurrio un error al quitar el producto";
            }
            return RedirectToAction("Carrito");
        }

        //Facturar
        public IActionResult Facturar(double total)
        {
            List<Det_boleta> carrito = JsonConvert.DeserializeObject<List<Det_boleta>>(HttpContext.Session.GetString("Carrito"));

            if (carrito == null)
            {
                return RedirectToAction("Catalogo");
            }

            ViewBag.mensaje = "Mensaje: " + det_BoletaADO.agregarDetBoleta(carrito, total);
            return RedirectToAction("ReporteBoleta");
        }

        public async Task<IActionResult> ReporteBoleta()
        {
            HttpContext.Session.SetString("Carrito", JsonConvert.SerializeObject(new List<Det_boleta>()));

            return View(await Task.Run(() => cab_BoletaADO.listarBoleta()));
        }

        public async Task<IActionResult> ReporteDetBoleta(int num_boleta)
        {
            return View(await Task.Run(() => det_BoletaADO.listarDetalles(num_boleta)));
        }

        public void contador()
        {
            IEnumerable<Det_boleta> carrito = JsonConvert.DeserializeObject<List<Det_boleta>>(HttpContext.Session.GetString("Carrito"));
            ViewBag.count = carrito.Count();
        }
    }
}

Restaurante_Delicias/Views/Ecommerce/Agregar.cshtml
@model Restaurante_Delicias.Models.Producto

@{
    ViewData["Title"] = "Producto Seleccionado";
}

<section class="py-5">
    <h1 class="text-center text-success">Producto Seleccionado</h1>
    <div class="container px-2 px-lg-5 mb-3">
        <div class="mx-auto">
            <h4>Producto</h4>
            <hr/>
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.id_prod)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.id_prod)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.nom_prod)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.nom_prod)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.desc_prod)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.desc_prod)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.precio)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.precio)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.cantidad)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.cantidad)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.desc_tipo)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.desc_tipo)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.foto)
                </dt>
                <dd class = "col-sm-10">
                    <img height="400px" width="400px" style="object-fit: cover;" src="@Url.Content(Model.foto)"/>
                </dd>
            </dl>
        </div>
        <div>
            @using (Html.BeginForm())
            {
                @Html.Hidden("id", Model.id_prod)
                <em>Ingrese la cantidad: </em>
                @Html.TextBox("Cantidad", 1)
                <input type="submit" value="Agregar" class="btn btn-primary"/>
                <a asp-action="Catalogo" asp-controller="Ecommerce" class="btn btn-primary">Volver al catalogo</a>
            }
        </div>
        <div>
            @ViewBag.mensaje
        </div>
    </div>
</section>

Restaurante_Delicias/Views/Ecommerce/Carrito.cshtml
@model IEnumerable<Restaurante_Delicias.Models.Det_boleta>

@{
    ViewData["Title"] = "Carrito";
}

<section class="py-5">
    <h1 class="text-center text-success">Carrito de Compra</h1>
    <div class="container px-2 px-lg-3 mt-5">
        <table class="table table-bordered table-hover text-center">
            <thead class="table-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.nom_prod)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.precio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.cantidad)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.importe)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.foto)
                    </th>
                    <th>Accion</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.ActionLink(item.nom_prod, "Agregar", new {id = item.id_prod})
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.precio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cantidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.importe)
                    </td>
                    <td>
                        <img height="60" src="@Url.Content(item.foto)"/>
                    </td>
                    <td>
                        @Html.ActionLink("Quitar", "Quitar", new { id = item.id_prod })
                    </td>
                </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <em>Importe a pagar S/.</em>
                    </td>
                    <td>
                        @ViewBag.total
                    </td>
                    <td>
                    </td>
                </tr>
            </tfoot>
        </table>
        <div>
            @ViewBag.mensaje
        </div>
        @Html.ActionLink("Facturar", "Facturar", new { total = @ViewBag.total }, new {@class="btn btn-success mr-2"})
        <a asp-action="Catalogo" asp-controller="Ecommerce" class="btn btn-primary">Seguir comprando</a>
    </div>
</section>

Restaurante_Delicias/Views/Ecommerce/Catalogo.cshtml
@model IEnumerable<Restaurante_Delicias.Models.Producto>

@{
    ViewData["Title"] = "Catalogo";
}

<section class="py-5">
    <h1 class="text-center text-success">Catalogo de Productos</h1>
    <div class="container px-2 px-lg-3 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            @foreach(var item in Model)
            {
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="imagen_producto card-img-top" src="@item.foto"/>
                        <!-- Product details-->
                        <div class="card-body pt-4 pb-2 px-3">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">
                                    @Html.DisplayFor(modelItem => item.nom_prod)
                                </h5>
                                <!-- Product price-->
                                <h5>
                                    S/. @Html.DisplayFor(modelItem => item.precio)
                                </h5>
                                <p style="text-align: justify" class="mt-2">
                                    @Html.DisplayFor(modelItem => item.desc_prod)
                                </p>
                                <p class="text-end fst-italic">
                                    @Html.DisplayFor(modelItem => item.desc_tipo)
                                </p>
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer border-top-0 bg-success">
                            <div class="text-center">
                                @Html.ActionLink("Agregar", "Agregar", new {id = item.id_prod}, new {@class="btn btn-outline-light my-2"})
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

Restaurante_Delicias/Views/Ecommerce/ReporteBoleta.cshtml
@model IEnumerable<Restaurante_Delicias.Models.Cab_boleta>

@{
    ViewData["Title"] = "ReporteBoleta";
}

<section class="py-5">
    <h1 class="text-center text-success">Boletas del Cliente</h1>
    <div class="container px-2 px-lg-3 mt-5">
        <table class="table table-bordered table-hover text-center">
            <thead class="table-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.num_boleta)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.id_cliente)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.fecha_boleta)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.total)
                    </th>
                    <th>
                        Consultar Detalles
                    </th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.num_boleta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id_cliente)
                    </td>
                    <td>
                        @Html.ValueFor(modelItem => item.fecha_boleta, "{0:dd/MM/yyyy}")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.total)
                    </td>
                    <td>
                        @Html.ActionLink("Detalles", "ReporteDetBoleta", new { num_boleta = item.num_boleta }, new {@class = "btn btn-primary"})
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</section>

Restaurante_Delicias/Views/Ecommerce/ReporteDetBoleta.cshtml
@model IEnumerable<Restaurante_Delicias.Models.Det_boleta>

@{
    ViewData["Title"] = "ReporteDetBoleta";
}

<section class="py-5">
    <h1 class="text-center text-success">Detalle de Boleta</h1>
    <div class="container px-2 px-lg-3 mt-5">
        <table class="table table-bordered table-hover text-center">
            <thead class="table-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.num_boleta)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.id_prod)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.cantidad)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.subtotal)
                    </th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.num_boleta)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id_prod)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cantidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.subtotal)
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</section>